/** Paleta inspirada en la UI de los juegos Pokémon (rojo, amarillo, azul, crema). */
export const colors = {
  bg: '#C8DCF0',
  bgPattern: '#B8CCE8',
  card: '#FFFFFF',
  cardBorder: '#1D2C5E',
  cardShadow: '#1D2C5E33',
  text: '#1A1A2E',
  textMuted: '#4A5A78',
  textOnPrimary: '#FFFFFF',
  textOnYellow: '#1A1A2E',
  accent: '#E3350D',
  accentDark: '#C62828',
  accentSoft: '#FFE8E6',
  accentYellow: '#FFCB05',
  accentYellowDark: '#E6B800',
  accentBlue: '#3B5DC9',
  accentBlueDark: '#2A4499',
  accentNavy: '#1D2C5E',
  headerGradientStart: '#E3350D',
  headerGradientMid: '#CC2A2A',
  headerGradientEnd: '#1D2C5E',
  success: '#3FA129',
  warning: '#F5A623',
  danger: '#E3350D',
  statHp: '#E3350D',
  statAtk: '#F57C00',
  statDef: '#FFCB05',
  statSpa: '#3B5DC9',
  statSpd: '#3FA129',
  statSpe: '#E91E8C',
  inputBg: '#FFFFFF',
  inputBorder: '#1D2C5E',
};

/** Alias legacy (tests / imports antiguos). */
export const Colors = {
  background: colors.bg,
  card: colors.card,
  border: colors.cardBorder,
  textPrimary: colors.text,
  textSecondary: colors.textMuted,
  accent: colors.accent,
  stats: {
    hp: colors.statHp,
    attack: colors.statAtk,
    defense: colors.statDef,
    specialAttack: colors.statSpa,
    specialDefense: colors.statSpd,
    speed: colors.statSpe,
  },
  effectiveness: {
    immune: '#6B7280',
    notVery: '#D97706',
    normal: '#4A5A78',
    superEff: '#3FA129',
  },
} as const;
